import { STAT_KEYS, validateGraph, type Dataset, type LonLat, type StatKey, type Territory } from '@empire/rules';
import type { LandResult } from './adjacency';
import type { CanonReport, TerritoryPlan } from './canon';
import { VALUE_METRICS, type CanonConfig, type SeaLaneConfig, type ValuesConfig } from './config';
import { EXPECTED_LAND_BORDERS, EXPECTED_SEA_LANES } from './expectations';
import type { MapResult, MapSettings } from './mapfile';
import { NE_URL } from './naturalearth';
import type { SeaLaneResult } from './sealanes';
import { fmt, type StatsResult } from './stats';
import type { TerrainResult } from './terrain';
import { pairKey } from './types';
import type { ValuesResult } from './values';

export interface ReportInput {
  dataset: Dataset;
  plans: TerritoryPlan[];
  canon: CanonReport;
  canonCfg: CanonConfig;
  land: LandResult;
  lanes: SeaLaneResult;
  laneCfg: SeaLaneConfig;
  stats: StatsResult;
  values: ValuesResult;
  valueCfg: ValuesConfig;
  terrain: TerrainResult;
  map: MapResult;
  mapSettings: MapSettings;
  sources: { neSha256: string; wbLastUpdated: string };
}

const STAT_LABELS: Record<StatKey, string> = {
  population: 'Population',
  areaKm2: 'Area (km²)',
  gdpNominalUsd: 'GDP nominal (US$)',
  gdpPppUsd: 'GDP PPP (intl $)',
  militarySpendingUsd: 'Military spending (US$)',
  armedForces: 'Armed forces',
};

type Cell = string | number;

/** Figures whose age matters for the value score; military data is sparse and yearly anyway. */
const CORE_STATS: readonly StatKey[] = ['population', 'areaKm2', 'gdpNominalUsd', 'gdpPppUsd'];

function table(headers: string[], rows: Cell[][]): string {
  const line = (cells: Cell[]) => `| ${cells.map((c) => String(c).replace(/\|/g, '\\|')).join(' | ')} |`;
  return [line(headers), line(headers.map(() => '---')), ...rows.map(line)].join('\n');
}

function heading(level: number, text: string): string[] {
  return ['', `${'#'.repeat(level)} ${text}`, ''];
}

function num(v: number | null): string {
  return v === null ? '—' : fmt(v);
}

function pt([lon, lat]: LonLat): string {
  return `${lon.toFixed(2)}, ${lat.toFixed(2)}`;
}

function bullets(lines: string[], empty: string): string {
  return lines.length === 0 ? empty : lines.map((l) => `- ${l}`).join('\n');
}

export function renderReport(r: ReportInput): string {
  const byId = new Map(r.dataset.territories.map((t) => [t.id, t]));
  const label = (id: string) => `${id} ${byId.get(id)?.name ?? ''}`.trim();
  return [
    `# Dataset ${r.dataset.version}: build report`,
    '',
    'Generated by `pnpm --filter @empire/data generate` from the files in `packages/data/config/`. ' +
      'Every judgment call below comes from those files; edit them and rebuild to change it.',
    ...summary(r),
    ...validation(r, byId),
    ...canon(r),
    ...seaLanes(r, label),
    ...values(r),
    ...statistics(r),
    ...terrain(r),
    ...adjacency(r),
  ].join('\n');
}

function summary(r: ReportInput): string[] {
  const { dataset, map, mapSettings: ms } = r;
  const kinds = [
    ['country', 'countries'],
    ['territory', 'territories'],
    ['region', 'regions'],
  ].map(([kind, plural]) => `${dataset.territories.filter((t) => t.kind === kind).length} ${plural}`);
  const landPairs = new Set(dataset.territories.flatMap((t) => t.land.map((n) => pairKey(t.id, n))));
  const manual = dataset.seaLanes.filter((l) => l.manual).length;
  const merges = r.plans.filter((p) => p.kind !== 'region' && p.members.length > 0).length;
  const regions = r.plans.filter((p) => p.kind === 'region').length;
  const replaced = r.stats.notes.filter((n) => n.includes('replaced World Bank')).length;
  const keptWhole = map.rings.keptWhole > 0 ? ` (${map.rings.keptWhole} sliver ring(s) kept whole)` : '';
  return [
    ...heading(2, 'Summary'),
    `- **${dataset.territories.length} territories**: ${kinds.join(', ')}.`,
    `- **${landPairs.size} land borders** and **${dataset.seaLanes.length} sea lanes** ` +
      `(${dataset.seaLanes.length - manual} automatic, ${manual} manual).`,
    `- **Map**: \`map.topo.json\` is ${Math.round(map.json.length / 1024)} KB with ` +
      `${map.points.after.toLocaleString('en')} points (from ${map.points.before.toLocaleString('en')}), ` +
      `${map.rings.after.toLocaleString('en')} rings. Visvalingam weight ≥ ${ms.minWeightPx2} px² on a 2400 px ` +
      `Natural Earth world map; islands ≥ ${ms.keepIslandKm2} km² and every member's main island kept${keptWhole}; ` +
      `quantization ${ms.quantization.toExponential(0)}.`,
    `- **Shapes**: Natural Earth 1:50m Admin 0 – Countries (${NE_URL}), ` +
      `sha256 \`${r.sources.neSha256.slice(0, 16)}…\`.`,
    `- **Statistics**: World Bank WDI, most recent non-empty value per indicator (API last updated ` +
      `${r.sources.wbLastUpdated}), plus the estimates listed below.`,
    `- **Hand edits** (review these first): ${merges} merges, ${regions} regions, ${r.canon.splits.length} splits, ` +
      `${r.canon.drops.length} dropped features; ${manual} manual sea lanes and ${r.lanes.removed.length} removed ` +
      `automatic ones; ${r.valueCfg.overrides.size} value overrides; ${replaced} World Bank figures replaced.`,
  ];
}

function validation(r: ReportInput, byId: ReadonlyMap<string, Territory>): string[] {
  const problems = validateGraph(r.dataset);
  const fixes = r.map.windingFixes;
  const check = (pairs: readonly [string, string][], has: (a: string, b: string) => boolean) =>
    pairs.map(([a, b]) => `${a}–${b} ${has(a, b) ? '✓' : '✗'}`).join(', ');
  const winding = fixes.length === 0 ? 'none needed' : fixes.join(', ');
  return [
    ...heading(2, 'Validation'),
    `- \`validateGraph\`: ${problems.length === 0 ? 'no problems' : problems.join('; ')}.`,
    `- Map geometry: ${r.dataset.territories.length} geometries, ids identical to the dataset, every one with ` +
      `area > 0 and wound so that d3.geoArea < 2π. Winding fixes: ${winding}.`,
    `- Well-known land borders: ${check(EXPECTED_LAND_BORDERS, (a, b) => byId.get(a)?.land.includes(b) ?? false)}.`,
    `- Expected sea lanes: ${check(EXPECTED_SEA_LANES, (a, b) => byId.get(a)?.sea.includes(b) ?? false)}.`,
  ];
}

function canon(r: ReportInput): string[] {
  const tally = (['kept', 'merged', 'bundled', 'dropped'] as const)
    .map((a) => `${r.canon.features.filter((f) => f.action === a).length} ${a}`)
    .join(', ');
  const members = (p: TerritoryPlan) => p.members.map((m) => `${m.name} (${m.id})`).join(', ');
  const builtFrom = (p: TerritoryPlan) =>
    p.pieces.map((x) => (x.key.includes('>') ? `split from ${x.source}` : `NE ${x.source}`)).join(', ');
  return [
    ...heading(2, 'Map canon'),
    "Boundaries follow Natural Earth's de facto drawing (for example Crimea inside Russia, Kashmir along the lines " +
      'of control), except where a split below moves polygons between territories. Every one of the ' +
      `${r.canon.features.length} Natural Earth features is accounted for; the build fails if one is not: ${tally}.`,
    ...heading(3, 'Territories played on their own (kind `territory`)'),
    table(
      ['Id', 'Name', 'Built from'],
      r.plans.filter((p) => p.kind === 'territory').map((p) => [p.id, p.name, builtFrom(p)]),
    ),
    ...heading(3, 'Merged into their sovereign'),
    table(
      ['Territory', 'Members folded in', 'Note'],
      r.plans
        .filter((p) => p.kind !== 'region' && p.members.length > 0)
        .map((p) => [`${p.id} ${p.name}`, members(p), p.note ?? '']),
    ),
    ...heading(3, 'Regions (bundles)'),
    table(
      ['Region', 'Members', 'Anchor', 'Note'],
      r.plans
        .filter((p) => p.kind === 'region')
        .map((p) => [`${p.id} ${p.name}`, members(p), p.anchor ? pt(p.anchor) : '', p.note ?? '']),
    ),
    ...heading(3, 'Splits (polygons moved out of a Natural Earth feature)'),
    table(
      ['Part', 'Name', 'Taken from', 'Now in', 'How', 'Polygons'],
      r.canon.splits.map((s) => [s.id, s.name, s.from, s.to, s.how, s.polygons]),
    ),
    ...heading(3, 'Dropped (not playable)'),
    table(
      ['NE code', 'NE name', 'Reason'],
      r.canon.drops.map((d) => [d.code, d.neName, d.reason]),
    ),
    ...heading(3, 'Names changed from Natural Earth'),
    table(
      ['Id', 'Natural Earth', 'Dataset'],
      r.canon.renamed.map((n) => [n.id, n.neName, n.name]),
    ),
    ...heading(3, 'Land border overrides'),
    bullets(r.land.notes, 'None: every land border comes straight from the shared-arc topology.'),
  ];
}

function seaLanes(r: ReportInput, label: (id: string) => string): string[] {
  const note = (l: SeaLaneResult['lanes'][number]) => {
    if (l.manual) return l.reason ?? '';
    return l.skipped > 0 ? `closest pair crossed ${l.blockedBy}; ${l.skipped} closer pair(s) skipped` : '';
  };
  const row = (l: SeaLaneResult['lanes'][number]): Cell[] => [
    label(l.a),
    label(l.b),
    l.km,
    l.manual ? 'manual' : 'auto',
    pt(l.from),
    pt(l.to),
    note(l),
  ];
  return [
    ...heading(2, 'Sea lanes'),
    'Automatic lanes join territories that are not land neighbors when their coastlines (arcs used by exactly one ' +
      `territory) come within **${r.laneCfg.thresholdKm} km**, unless every connecting segment crosses a third ` +
      "territory's land. Manual lanes come from `config/sea-lanes.yaml` and use the closest coastline points (or the " +
      'coastline nearest a hand-given point) with no distance limit. From/To are the drawn endpoints.',
    '',
    table(['A', 'B', 'km', 'Type', 'From (A)', 'To (B)', 'Note'], r.lanes.lanes.map(row)),
    ...heading(3, 'Automatic lanes removed by hand'),
    r.lanes.removed.length === 0
      ? 'None.'
      : table(
          ['A', 'B', 'km', 'Reason'],
          r.lanes.removed.map((x) => [label(x.a), label(x.b), x.km, x.reason]),
        ),
    ...heading(3, 'Pairs within range but blocked by third-party land'),
    r.lanes.blocked.length === 0
      ? 'None.'
      : table(
          ['A', 'B', 'Closest km', 'Blocked by'],
          r.lanes.blocked.map((x) => [label(x.a), label(x.b), x.km, x.blockedBy]),
        ),
    ...(r.lanes.notes.length > 0 ? [...heading(3, 'Config notes'), bullets(r.lanes.notes, '')] : []),
  ];
}

function values(r: ReportInput): string[] {
  const { rows, targets } = r.values;
  const weights = VALUE_METRICS.map((m) => `${m} ${r.valueCfg.weights[m]}`).join(', ');
  const counts = new Map<number, number>();
  for (const t of r.dataset.territories) counts.set(t.value, (counts.get(t.value) ?? 0) + 1);
  const histogram: string[] = [];
  for (let v = 10; v >= 1; v--) {
    const n = counts.get(v) ?? 0;
    const bar = '█'.repeat(n).padEnd(40);
    histogram.push(`${String(v).padStart(2)} │ ${bar} ${String(n).padStart(3)}  (target ${targets.get(v) ?? 0})`);
  }
  const partial = rows
    .filter((row) => row.metrics.length < VALUE_METRICS.length)
    .map((row) => `${row.id} (${VALUE_METRICS.filter((m) => !row.metrics.includes(m)).join(', ')} missing)`);
  const overridden = rows
    .filter((row) => row.override !== null)
    .map((row) => `**${row.id}** ${row.generated} → ${row.value} (${row.overrideReason ?? 'no reason given'})`);
  return [
    ...heading(2, 'Game values'),
    `Score = weighted mean of min–max normalized log10 metrics (weights: ${weights}); a missing metric drops out ` +
      'and the remaining weights are renormalized. Values are assigned by rank against the target distribution, ' +
      'then `overrides` in `config/values.yaml` are applied.',
    '',
    '```',
    ...histogram,
    '```',
    '',
    ...(partial.length > 0
      ? [
          'Scored on fewer metrics because of missing data (renormalizing can flatter a territory that lacks GDP): ' +
            `${partial.join('; ')}.`,
          '',
        ]
      : []),
    ...(overridden.length > 0 ? [`Overrides: ${overridden.join('; ')}.`, ''] : []),
    table(
      ['#', 'Id', 'Name', 'Score', 'Population', 'Area km²', 'GDP US$', 'GDP PPP', 'Generated', 'Override', 'Final'],
      rows.map((row, i) => [
        i + 1,
        row.id,
        row.name,
        row.score.toFixed(4),
        num(row.inputs.population),
        num(row.inputs.areaKm2),
        num(row.inputs.gdpNominalUsd),
        num(row.inputs.gdpPppUsd),
        row.generated,
        row.override ?? '',
        row.value,
      ]),
    ),
  ];
}

function statistics(r: ReportInput): string[] {
  const territories = r.dataset.territories;
  const coverage = STAT_KEYS.map((k) => [
    STAT_LABELS[k],
    territories.filter((t) => t.stats[k] !== null && !t.statMeta[k].estimated).length,
    territories.filter((t) => t.stats[k] !== null && t.statMeta[k].estimated).length,
    territories.filter((t) => t.stats[k] === null).length,
  ]);
  const estimated: Cell[][] = [];
  const old: string[] = [];
  for (const t of territories) {
    for (const k of STAT_KEYS) {
      const v = t.stats[k];
      const m = t.statMeta[k];
      if (v !== null && m.estimated) estimated.push([t.id, STAT_LABELS[k], fmt(v), m.year ?? '', m.source]);
      if (v !== null && m.year !== null && m.year <= 2020 && CORE_STATS.includes(k)) {
        old.push(`${t.id} ${STAT_LABELS[k]} (${m.year})`);
      }
    }
  }
  const missing = STAT_KEYS.flatMap((k) => {
    const list = territories.filter((t) => t.stats[k] === null);
    if (list.length === 0) return [];
    const why = (t: Territory) => {
      const source = t.statMeta[k].source;
      return source === 'No data' ? t.id : `${t.id} (${source})`;
    };
    return [`**${STAT_LABELS[k]}** (${list.length}): ${list.map(why).join(', ')}`];
  });
  return [
    ...heading(2, 'Real-world statistics'),
    'World Bank figures are the most recent non-empty value per indicator. Territories made of several economies ' +
      'sum them; a sum is withheld (null) when members without the figure hold 10% or more of the population. ' +
      'Military figures are plain sums, since dependencies have no forces of their own.',
    '',
    table(['Stat', 'World Bank only', 'Estimated or computed', 'Missing (null)'], coverage),
    ...heading(3, 'Estimated or computed figures'),
    table(['Id', 'Stat', 'Value', 'Year', 'Source'], estimated),
    ...heading(3, 'Missing figures'),
    bullets(missing, 'None.'),
    ...heading(3, 'Old figures (data year 2020 or earlier)'),
    old.length === 0 ? 'None.' : old.join(', '),
    ...heading(3, 'Replacements, adjustments and notes'),
    bullets(r.stats.notes, 'None.'),
  ];
}

function terrain(r: ReportInput): string[] {
  const tagged = (tag: 'island' | 'mountains') =>
    r.dataset.territories.filter((t) => t.terrain.includes(tag)).map((t) => t.id);
  const micro = r.dataset.territories.filter((t) => t.micro).map((t) => t.id);
  const threshold = r.canonCfg.micro.areaKm2.toLocaleString('en');
  return [
    ...heading(2, 'Terrain and micro territories'),
    `- **Islands** (${tagged('island').length}): ${tagged('island').join(', ')}`,
    `  - automatic (no land neighbors): ${r.terrain.autoIslands.length}; see \`config/terrain.yaml\` for the rest.`,
    `- **Mountains** (${tagged('mountains').length}): ${tagged('mountains').join(', ')}`,
    `- **Micro** (dot on the map; regions and area < ${threshold} km², ${micro.length}): ${micro.join(', ')}`,
    ...r.terrain.notes.map((n) => `- ${n}`),
  ];
}

function adjacency(r: ReportInput): string[] {
  return [
    ...heading(2, 'Adjacency'),
    table(
      ['Id', 'Name', 'Kind', 'Value', 'Land', 'Sea'],
      r.dataset.territories.map((t) => [
        t.id,
        t.name,
        t.kind,
        t.value,
        t.land.join(' ') || '—',
        t.sea.join(' ') || '—',
      ]),
    ),
  ];
}
